---
title: "P8105 (Data Science I): Homework 3"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

theme_set(theme_bw())
```

## Problem 1

#### Importing and cleaning BRFSS data 

```{r importing brfss data}
brfss_data <- p8105.datasets::brfss_smart2010 %>% 
  janitor::clean_names()

brfss_data <- brfss_data %>% 
  rename(state = locationabbr, 
         location = locationdesc) %>% 
  filter(topic == "Overall Health") %>% 
  select(-(class:question), 
                       -sample_size, 
                       -(confidence_limit_low:geo_location)) %>% 
  mutate(response = as.factor(response))
```

#### Questions and plots

```{r calculating 7 obs in 2002}
brfss_data %>% 
  filter(year == 2002) %>% 
  distinct(state, location) %>% 
  count(state) %>% 
  filter(n == 7)
```

- In 2002, the states Connecticut, Florida, and North Carolina were observed at 7 locations. 

```{r creating spaghetti plot, fig.height = 7, fig.width = 9, fig.align = "center"}
brfss_data %>% 
  group_by(state, year) %>% 
  summarize(n_obs = n()) %>% 
  ggplot(aes(x = year, y = n_obs)) + 
    geom_line(aes(color = state)) + 
    viridis::scale_color_viridis(
      name = "", 
      discrete = TRUE) +
    labs(x = "Year", 
         y = "Number of observations") + 
    theme(legend.position = "bottom", 
          legend.direction = "horizontal") + 
    guides(color = guide_legend(ncol = 17))
```

```{r table proportion excellent responses NY 2002/06/10, fig.align = "center"}
brfss_data %>% 
  filter(year %in% c(2002, 2006, 2010), 
         state == "NY") %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  mutate(prop_excel =  (excellent) / (excellent + fair + good + poor + very_good)) %>% 
  group_by(year) %>% 
  summarize("Average proportion excellent" = round(mean(prop_excel), 4), 
            "Standard deviation" = round(sd(prop_excel), 4)) %>% 
  knitr::kable()
```

```{r average proportion, response category across location by state, warning = FALSE, fig.height = 8, fig.align = "center", dpi = 300}
library(patchwork)

avg_response_year_state <- 
  brfss_data %>%
  mutate(year = as.factor(year)) %>% 
  group_by(year, state, response) %>%
  summarize(avg_response = mean(data_value))

poor_dist <- avg_response_year_state %>%
  filter(response == "Poor") %>%
  ggplot(aes(x = avg_response, fill = year)) +
    geom_density(alpha = 0.5, color = NA) + 
    geom_text(x = 0, y = 0.40, 
              label = "Poor", size = 3.5) + 
    scale_x_continuous(limits = c(0, 45), 
                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)) + 
    viridis::scale_fill_viridis(discrete = TRUE, 
                                option = "magma",
                                guide = FALSE) + 
    theme(axis.text.x = element_blank(), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    labs(y = "", x = "")

fair_dist <- avg_response_year_state %>%
  filter(response == "Fair") %>%
  ggplot(aes(x = avg_response, fill = year)) +
    geom_density(alpha = 0.5, color = NA) +
    geom_text(x = 0, y = 0.15, 
              label = "Fair", size = 3.5) + 
    scale_x_continuous(limits = c(0, 45), 
                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)) + 
    viridis::scale_fill_viridis(discrete = TRUE, 
                                option = "magma",
                                guide = FALSE) + 
    theme(axis.text.x = element_blank(), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    labs(y = "", x = "")

good_dist <- avg_response_year_state %>%
  filter(response == "Good") %>%
  ggplot(aes(x = avg_response, fill = year)) +
    geom_density(alpha = 0.5, color = NA) +
    geom_text(x = 0, y = 0.15, 
              label = "Good", size = 3.5) + 
    scale_x_continuous(limits = c(0, 45), 
                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)) + 
    viridis::scale_fill_viridis(discrete = TRUE, 
                                option = "magma", 
                                guide = FALSE) + 
    theme(axis.text.x = element_blank(), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) +
    labs(y = "", x = "") 

v_good_dist <- avg_response_year_state %>%
  filter(response == "Very good") %>%
  ggplot(aes(x = avg_response, fill = year)) +
    geom_density(alpha = 0.5, color = NA) +
    geom_text(x = 1, y = 0.125, 
              label = "Very good", size = 3.5) + 
    scale_x_continuous(limits = c(0, 45), 
                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)) + 
    viridis::scale_fill_viridis(discrete = TRUE, 
                                option = "magma",
                                guide = FALSE) + 
    theme(axis.text.x = element_blank(), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    labs(y = "", x = "")

excel_dist <- avg_response_year_state %>%
  filter(response == "Excellent") %>%
  ggplot(aes(x = avg_response, fill = year)) +
    geom_density(alpha = 0.5, color = NA) +
    geom_text(x = 1, y = 0.15, 
              label = "Excellent", size = 3.5) + 
    scale_x_continuous(limits = c(0, 45), 
                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)) + 
    labs(y = "", x = "Response proportion") +
    viridis::scale_fill_viridis(name = "Year",
                                discrete = TRUE, 
                                option = "magma") + 
    theme(legend.position = "bottom",
          legend.direction = "horizontal", 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    guides(fill = guide_legend(ncol = 10)) 
    

poor_dist / fair_dist / good_dist / v_good_dist / excel_dist
```


## Problem 2

```{r}
insta_data <- p8105.datasets::instacart %>% 
  janitor::clean_names()
```

```{r aisles information}
insta_data %>% 
  distinct(aisle_id) %>% 
  count()

numb_orders <- insta_data %>%
  group_by(aisle) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
```

```{r items ordered in each aisle, fig.height = 15, fig.align = "center", dpi = 300}
numb_orders %>% 
  mutate(aisle = forcats::fct_reorder(aisle, n, .desc = TRUE)) %>% 
  ggplot(aes(x = aisle, y = n)) + 
  coord_flip() + 
  geom_bar(stat = "identity", fill = "#456355") +
    labs(y = "Number of Orders", 
        x = "Aisle") + 
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) 
```

```{r mean hour of the day}
insta_data %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  select(product_name, order_dow, order_hour_of_day) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(avg_hour = round(mean(order_hour_of_day)), 4) %>%
  spread(key = order_dow, value = avg_hour) %>% 
  knitr::kable()
```

## Problem 3

```{r importing and cleaning NY NOAA data}
noaa_data <- p8105.datasets::ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, c("year", "month", "day"), sep = "-") %>% 
  mutate(tmax = as.double(tmax) / 10, 
         tmin = as.double(tmin) / 10, 
         prcp = prcp / 10,
         month = month.name[as.integer(month)], 
         year = as.integer(year))
```

```{r average snow}
noaa_data %>% 
  group_by(month) %>% 
  summarize(avg_snow = round(mean(snow, na.rm = TRUE), 4))
```

```{r dpi = 300,fig.align = "center", fig.retina = 1}
avg_daily_temp <- noaa_data %>%
  filter(month %in% c("January", "July")) %>%
  mutate(avg_temp = (tmin + tmax) / 2)

avg_daily_temp %>% 
  filter(month %in% c("January", "July")) %>% 
  group_by(year, month) %>% 
  summarize(avg_temp = mean(avg_temp, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = avg_temp)) + 
    geom_line(color = "#7496D2", size = 1) + 
  facet_grid(~ month, 
             scales = "free") + 
  labs(x = "Year", 
       y = "Average Daily Temperature (degrees C)") + 
  theme(axis.text.x = element_text(angle = 45,
                                   vjust = 0.4), 
        strip.background = element_rect(fill = "black"), 
        strip.text = element_text(color = "white", 
                                  face = "bold"))
```

